- name: ensure not running all tasks with sudo
  fail:
    msg: "Do not run all tasks with sudo"
  when:
    - ansible_env.USER == "root"
  tags: always

- block:
    #- name: pip3 - install black
    #  pip:
    #    name: "{{ ansible_loop.allitems }}"
    #    executable: pip3
    #    state: latest
    #    extra_args: --user
    #  loop_control:
    #    extended: yes
    #  loop:
    #    - black
    #  tags: ['pip', 'pip3', 'python']
    #  when: not ansible_distribution == "Fedora"

    - name: Fedora - install packages
      become: yes
      package:
        name:
          - black
          - powerline-fonts
        state: present
      tags: ['black', 'airline']
      when: ansible_distribution == "Fedora"

  tags: ['black', 'vim']

- block:
    - name: create directories
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        owner: "{{ ansible_env.USER }}"
        mode: 0700
      with_items:
        - ".vim"
        - ".vim/autoload"

    - name: vim-plug - plug.vim
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "{{ item }}"
        owner: "{{ ansible_env.USER }}"
        mode: 0640
      loop:
        - "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"

    - name: copy vimrc
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        owner: "{{ ansible_env.USER }}"
        mode: 0600
      with_items:
        - vimrc

    - name: copy nvim init.vim
      template:
        src: "nvim-init.vim.j2"
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
        owner: "{{ ansible_env.USER }}"
        mode: 0600

    - name: install plugins
      command: 'vim +PlugInstall +qall'
      tags: plugins

    - name: copy supplemental file(s)
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/.vim/{{ item }}"
        owner: "{{ ansible_env.USER }}"
        mode: 0600
      with_items:
        - filetype.vim

  tags: vim
