- name: ensure not running all tasks with sudo
  ansible.builtin.fail:
    msg: "Do not run all tasks with sudo"
  when:
    - ansible_env.USER == "root"
  tags: always

- block:
    - name: Linux - install black (pip3)
      pip:
        name: "{{ ansible_loop.allitems }}"
        executable: pip3
        state: latest
        extra_args: '--user --upgrade --no-cache-dir'
      loop_control:
        extended: yes
      loop:
        - ansible-lint
        - black
      tags: ['pip', 'pip3', 'python']
      when:
        - ansible_facts['system'] == "Linux"
        - not ansible_facts['distribution'] == "Fedora"

    - name: Linux - install packages
      become: true
      ansible.builtin.package:
        name:
          - gcc
          - git
          - golang-x-tools-gopls
          - python3-isort
          - "{{ nodejs_package_name }}"
          - powerline-fonts
          - ShellCheck
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Linux - install packages (Fedora)
      become: true
      ansible.builtin.dnf:
        name:
          - black
          - cascadia-code-nf-fonts
          - cascadia-mono-nf-fonts
          - neovim
          - python3-ansible-lint
          - python3-neovim
          - uv
        state: latest
      when: ansible_distribution == "Fedora"

    - name: macOS - install homebrew packages
      community.general.homebrew:
        name:
          - 'isort'
          - 'npm'
          - 'shellcheck'
          - 'stylua'
          - 'yamlfmt'
        state: latest
      tags: ['brew', 'homebrew']
      when: ansible_facts['distribution'] == "MacOSX"

    - name: Install node.js packages globally
      become: true
      community.general.npm:
        name: "{{ item }}"
        global: true
      tags: ['lsp', 'npm']
      loop:
        - '@ansible/ansible-language-server'
        - 'bash-language-server'
        - 'pyright'

    - name: Install additional dependencies
      ansible.builtin.import_tasks: additional_dependencies.yml 
      tags: ['additional_dependencies']

  tags: ['vim', 'install', 'dependencies']

- block:
    - name: create directories
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        owner: "{{ ansible_env.USER }}"
        mode: 0700
      loop:
        - ".vim"
        - ".config/nvim"
        - ".config/nvim/lsp"
        - ".config/nvim/lua"
        - ".config/nvim/lua/config"
        - ".config/nvim/lua/plugins"

    - name: copy neovim config file(s)
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        owner: "{{ ansible_env.USER }}"
        mode: 0600
      loop:
        - 'config/nvim/init.lua'
        - 'config/nvim/lsp/pyright.lua'
        - 'config/nvim/lsp/terraformls.lua'
        - 'config/nvim/lua/config/lazy.lua'
        - 'config/nvim/lua/config/lsp.lua'
        - 'config/nvim/lua/config/options.lua'
        - 'config/nvim/lua/plugins/conform.lua'
        - 'config/nvim/lua/plugins/init.lua'
        - 'config/nvim/lua/plugins/nvim-lspconfig.lua'
        - 'config/nvim/lua/plugins/nvim-lualine.lua'
        - 'config/nvim/lua/plugins/nvim-telescope.lua'
        - 'config/nvim/lua/plugins/nvim-treesitter.lua'
        - 'config/nvim/lua/plugins/vim-fugitive.lua'

  tags: ['vim', 'config']

- name: zellij - import tasks
  import_tasks: zellij.yml
  become: true
  when: zellij|bool
  tags: zellij

