- name: ensure not running all tasks with sudo
  fail:
    msg: "Do not run all tasks with sudo"
  when:
    - ansible_env.USER == "root"
  tags: always

- block:
    - name: pip3 - install black
      pip:
        name: "{{ ansible_loop.allitems }}"
        executable: pip3
        state: latest
        extra_args: --user
      loop_control:
        extended: yes
      loop:
        - black
      tags: ['pip', 'pip3', 'python']
      when: not ansible_distribution == "Fedora"

    - name: Fedora - install black
      become: yes
      package:
        name:
          - black
        state: present
      tags: ['black', 'airline']
      when: ansible_distribution == "Fedora"

  tags: ['black', 'vim']

- block:
    - name: create directories
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        owner: "{{ ansible_env.USER }}"
        mode: 0700
      with_items:
        - ".vim"
        - ".vim/autoload"

    - name: vim-plug - plug.vim
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
        owner: "{{ ansible_env.USER }}"
        mode: 0640

    - name: copy vimrc
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        owner: "{{ ansible_env.USER }}"
        mode: 0600
      with_items:
        - vimrc

    - name: install plugins
      command: 'vim +PlugInstall +qall'
      tags: plugins

    - name: copy supplemental file(s)
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/.vim/{{ item }}"
        owner: "{{ ansible_env.USER }}"
        mode: 0600
      with_items:
        - filetype.vim

  tags: vim
