vim.highlight.priorities.semantic_tokens = 95 -- treesitter's priority level is 100
vim.g.mapleader = " "
vim.opt.laststatus = 2
vim.opt.mouse = ""
vim.opt.showtabline = 2
vim.opt.showmode = false
vim.opt.signcolumn = "yes" -- prevent layout shift when lsp diagnotics shown
vim.opt.termguicolors = true
vim.opt.backspace = { "indent", "eol", "start" }
